// Code generated by go-swagger; DO NOT EDIT.

// Package restapi IskayPet Code Challenge
//
//	API definition of the code challenge proposed.
//	Useful links - [GitHub project](https://github.com/AMAndres/iskaypetchallenge) - [Swagger PetStore editor](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml)
//	Terms Of Service:
//	  --
//	Schemes:
//	  http
//	Host: github.com
//	BasePath: /AMAndres/iskaypetchallenge/docs
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: <arenas.macineira.andres@gmail.com>
//
//	Consumes:
//	  - application/json
//	  - application/x-www-form-urlencoded
//	  - application/xml
//
//	Produces:
//	  - application/json
//	  - application/xml
//
// swagger:meta
package restapi
