// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Pet pet
//
// swagger:model Pet
type Pet struct {

	// birthday
	// Example: 2017-01-01
	// Required: true
	// Format: date
	Birthday *strfmt.Date `json:"birthday"`

	// gender
	// Required: true
	// Maximum: 1
	// Minimum: 0
	Gender *int64 `json:"gender"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// name
	// Example: faro
	// Required: true
	Name *string `json:"name"`

	// species
	// Maximum: 1
	// Minimum: 0
	Species *int64 `json:"species,omitempty"`
}

// Validate validates this pet
func (m *Pet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBirthday(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpecies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pet) validateBirthday(formats strfmt.Registry) error {

	if err := validate.Required("birthday", "body", m.Birthday); err != nil {
		return err
	}

	if err := validate.FormatOf("birthday", "body", "date", m.Birthday.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Pet) validateGender(formats strfmt.Registry) error {

	if err := validate.Required("gender", "body", m.Gender); err != nil {
		return err
	}

	if err := validate.MinimumInt("gender", "body", *m.Gender, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("gender", "body", *m.Gender, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Pet) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Pet) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Pet) validateSpecies(formats strfmt.Registry) error {
	if swag.IsZero(m.Species) { // not required
		return nil
	}

	if err := validate.MinimumInt("species", "body", *m.Species, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("species", "body", *m.Species, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pet based on context it is used
func (m *Pet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pet) UnmarshalBinary(b []byte) error {
	var res Pet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
